# -*- coding: utf-8 -*-
"""DSP_AlterVoice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ntWrjnjpFEB6MZC2_d-a89xcLNkMgEL
"""

from google.colab import drive
drive.mount('/content/drive')

import librosa
import soundfile as sf
import noisereduce as nr

# Load the pre-recorded voice file (replace 'input_voice.wav' with your file path)
input_path = '/content/drive/MyDrive/DSP_VR(NO NOISE)/Record10_STAN-enhanced.wav'
output_path = '/content/drive/MyDrive/DSP_AlteredVoice/Record10_STAN-Altered.wav'

# Load the audio file using librosa
y, sr = librosa.load(input_path, sr=None)

# Apply noise reduction using noisereduce
y_denoised = nr.reduce_noise(y=y, sr=sr)

# Change the pitch using librosa's pitch shifting function
y_shifted = librosa.effects.pitch_shift(y_denoised, sr=sr, n_steps=5)  # Change n_steps to adjust the pitch

# Save the altered voice to a file
sf.write(output_path, y_shifted, sr)

# Play the altered voice (optional)
import IPython.display as ipd
ipd.Audio(output_path)